### PR TITLE
Fix: Preventing forward scrubbing (fixes: #319)

### LINKED ISSUE #319: Fully preventing forward scrubbing
### Subject of the issue/enhancement/features
It seems that learners are bypassing the `_preventForwardScrubbing` setting by interacting with the locked media player scrub bar. Despite the setting being enabled, a small number of learners repeatedly select the scrub bar and are able to skip forward in the video, essentially bypassing the need to watch the content in full.

The issue likely stems from the current solution, which forces the scrub bar to the furthest point of progress, but this approach isn't fully effective. A more robust solution would be to ensure that the locked scrub bar is not interactable or selectable at all.

### Your environment
* FW v5.35.3
* Media v6.6.0

### Steps to reproduce
I'm not entirely sure how to reliably reproduce this issue. It seems to occur intermittently with a small subset of learners, but they are able to repeatedly bypass the locked media player by interacting with the scrub bar.

### Expected behaviour
When `_preventForwardScrubbing` is enabled, the scrub bar should be completely disabled, preventing any interaction, including clicks, dragging, or selection. The scrub bar should be non-interactive for all learners.

### Actual behaviour
Currently, the scrub bar remains selectable by mouse, allowing users to interact with it and potentially bypass media content, even with `_preventForwardScrubbing` enabled.

### PR DESCRIPTION
**Pull request by joe-replin**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)

It seems that learners are bypassing the `_preventForwardScrubbing` setting by interacting with the locked media player scrub bar. Despite the setting being enabled, a small number of learners repeatedly select the scrub bar and are able to skip forward in the video, essentially bypassing the need to watch the content in full.

The issue likely stems from the current solution, which forces the scrub bar to the furthest point of progress, but this approach isn't fully effective. A more robust solution would be to ensure that the locked scrub bar is not interactable or selectable at all.

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* Fixes #319 
* No pointer events prevents mouse and touch events.
* Prevent default blocks the scrub bar from being changed programmatically.
* aria-disabled makes the scrub bar non-focusable.

I'm only taking a good stab at this being a good solution to truly lock down forward scrubbing. As stated in #319, I'm not sure how the current locks are being bypassed. 

[//]: # (List appropriate steps for testing if needed)
### Testing
Try to break it!

[//]: # (Mention any other dependencies)

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by oliverfoster — COMMENTED** [review]
Would you not want to use all methods, just for peace of mind? And seeing as the code is there still.

**Comment by joe-replin** [comment]
Added back in!

**Comment by joe-replin** [comment]
@swashbuck, please see latest changes for readability and review.

File: js/mediaView.js [hunk 1]
```diff
@@ -521,6 +515,25 @@ class MediaView extends ComponentView {
     Adapt.trigger('media:transcript', 'complete', this);
   }
 
+  /**
+   * This function ensures that users cannot skip ahead in the media until they have watched it fully if `_preventForwardScrubbing` is enabled.
+   */
+  preventForwardScrubbing() {
+    if ((this.model.get('_preventForwardScrubbing')) && (!this.model.get('_isComplete'))) {
```
Comment (oliverfoster) [inline js/mediaView.js:522]: Return early

File: js/mediaView.js [hunk 2]
```diff
@@ -521,6 +515,25 @@ class MediaView extends ComponentView {
...
+        timeupdate: this.onMediaElementTimeUpdate
+      });
+
+      const timeSlider = this.$('.mejs__time-slider')[0];
+      if (timeSlider) {
+        timeSlider.style.pointerEvents = 'none';
+        timeSlider.addEventListener('input', (e) => e.preventDefault());
+        timeSlider.setAttribute('aria-disabled', 'true');
+      }
+    }
```
Comment (oliverfoster) [inline js/mediaView.js:534]: return early:
```suggestion
    if (!this.model.get('_preventForwardScrubbing') || this.model.get('_isComplete')) return;
    $(this.mediaElement).on({
      seeking: this.onMediaElementSeeking,
      timeupdate: this.onMediaElementTimeUpdate
    });
    const timeSlider = this.$('.mejs__time-slider')[0];
    if (timeSlider) {
      timeSlider.style.pointerEvents = 'none';
      timeSlider.addEventListener('input', (e) => e.preventDefault());
      timeSlider.setAttribute('aria-disabled', 'true');
    }
```

**Review by oliverfoster — APPROVED** [review]

File: js/mediaView.js [hunk 3]
```diff
@@ -521,6 +515,23 @@ class MediaView extends ComponentView {
...
+    $(this.mediaElement).on({
+      seeking: this.onMediaElementSeeking,
+      timeupdate: this.onMediaElementTimeUpdate
+    });
+    const timeSlider = this.$('.mejs__time-slider')[0];
+    if (timeSlider) {
+      timeSlider.style.pointerEvents = 'none';
+      timeSlider.addEventListener('input', (e) => e.preventDefault());
+      timeSlider.setAttribute('aria-disabled', 'true');
+    }
```
Comment (swashbuck) [inline js/mediaView.js:532]: Return early here
```suggestion
    if (!timeSlider) return;
    timeSlider.style.pointerEvents = 'none';
    timeSlider.addEventListener('input', (e) => e.preventDefault());
    timeSlider.setAttribute('aria-disabled', 'true');
```

**Review by swashbuck — APPROVED** [review]
👍
