### PR TITLE
 New: Added event trigger (fixes: #264)

### LINKED ISSUE #264: Volume & Mute Event Trigger
### Subject of the issue/enhancement/features
I would like to add event triggers to this plug-in for the purposes of picking up on them for other means to enhance experiences & capabilities. More specifically, I want to track the mute state and volume value of each interaction with the player.

### PR DESCRIPTION
**Pull request by joe-replin**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### New
* Adds trigger to volume controls to indicate the mute state and current volume value
* Fixes #264 

[//]: # (List appropriate steps for testing if needed)
### Testing
1. Install PR and use browser console to test.

[//]: # (Mention any other dependencies)

### CODE REVIEW

**Review by joe-allen-89 — APPROVED** [review]

File: js/mediaView.js [hunk 1]
```diff
@@ -481,6 +482,10 @@ class MediaView extends ComponentView {
     }
   }
 
+  onMediaVolumeChange(event) {
+    Adapt.trigger('media:volumeChange', this, this.mediaElement.muted, this.mediaElement.volume);
```
Comment (oliverfoster) [inline js/mediaView.js:486]: How does this signify which media is changed?
You're passing `[view, muted, volume]`, would `[_id, muted, volume]` not be easier to use where consumed?

Comment (joe-replin) [reply js/mediaView.js:486]: Hey @oliverfoster, this is so whatever is on the receiving end has the options available to read more into the model data. Sometimes we'll want available access to the _id, title, lang, displayTitle, model type, etc.
https://github.com/adaptlearning/adapt-contrib-xapi/blob/8b375def92ba6da3eea14e710b734f1a8373c8b4/js/XAPI.js#L670
https://github.com/cgkineo/adapt-xAPI/blob/ea9400ecb5cf0c18487d04dbe5247f849f2c863d/js/statements/abstractStatementModel.js#L24

Comment (oliverfoster) [reply js/mediaView.js:486]: Did you mean to pass the model instead of the view?
```suggestion
    Adapt.trigger('media:volumeChange', this.model, this.mediaElement.muted, this.mediaElement.volume);
```

Comment (joe-replin) [reply js/mediaView.js]: Ah, I see how that would be more efficient. Thanks :)
